
# Test putting atlases in a different location
nunaliit::atlas_parent_directory: "/tmp/apps-nunaliit-atlases-%{environment}"

# Test putting couchdbs in a different location
nunaliit::couchdb_data_directory: "/tmp/apps-nunaliit-couchdbs-%{environment}-%{hiera('project')}"

